# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppeBike' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppeBike

  target 'AppeBike-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppeBikeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AppeBike-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppeBike-tvOS

  target 'AppeBike-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
